"""Add city, state, zip_code to restaurants

Revision ID: 421431697b4c
Revises: 63eb7ab17be0
Create Date: 2025-09-08 09:56:16.076910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421431697b4c'
down_revision = '63eb7ab17be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
