"""Add diet_type to menu_items

Revision ID: deeb1c110f00
Revises: 421431697b4c
Create Date: 2025-09-08 21:56:02.514535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deeb1c110f00'
down_revision = '421431697b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_type', sa.Enum('veg', 'non-veg'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('diet_type')

    # ### end Alembic commands ###
